phase1: remove renderable locks: not supported in 0.8.9
Support for renderable locks was only added in buildbot 0.9.0

0.8.9 fails with:

	  File "/usr/lib/python2.7/dist-packages/buildbot/process/buildstep.py", line 266, in startStep
	    for access in self.locks]
	exceptions.TypeError: '_Renderer' object is not iterable

Signed-off-by: Thibaut VARÈNE <hacks@slashdirt.org>